#!/bin/sh
#
#  pwshx
#
#  Author:
#       Roman M. Yagodin <roman.yagodin@gmail.com>
#
#  Copyright (c) 2018 Roman M. Yagodin
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

if ! [ -x "$(command -v pwsh)" ]; then
    echo "Error: PowerShell not found!"
    exit 1
fi

if [ "$1" = "-t" ]; then
    shift 1
    export PWSHX_IN_TERMINAL=true
    x-terminal-emulator -e pwsh "$@"
else
    pwsh "$@"
fi
